version: "3.8"

services:
  app:
    container_name: go-dev
    image: go-dev
    restart: unless-stopped
    build: 
      context: .
      target: build
    ports:
      - 8000:8000
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ISSUER=${ISSUER}
      - CLIENT_ID=${CLIENT_ID}
    depends_on:
      - dbpostgres
    networks:
      - community-network
    
  dbpostgres:
    container_name: go-database
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data/
    networks:
      - community-network
    
volumes:
  data:

networks:
  community-network:
    driver: bridge