# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: community-tracker-golang Build & Deploy

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    
jobs:
  build:
    name: Build Docker Container
    
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://communitytrackeracr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: communitytrackeracr.azurecr.io/ct/community-tracker-golang:${{ github.sha }}
        file: ./Dockerfile
